apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
  namespace: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx-ingressroute.poddle.uz`)
      kind: Rule
      services:
        - name: nginx-service
          port: 80
  tls:
    secretName: wildcard-poddle-uz-tls-secret
