crds:
  enabled: true

configInline:
  address-pools:
    - name: ip-address-pool
      protocol: layer2
      addresses:
        - 192.168.31.10-192.168.31.19

  l2-advertisements:
    - name: l2-adver-tisement
      ipAddressPools:
        - ip-address-pool
