apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: vault-secrets-operator
spec:
  address: http://192.168.31.247:8200
  skipTLSVerify: true
---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultAuth
# metadata:
#   name: vault-auth
#   namespace: vault-secrets-operator
# spec:
#   method: kubernetes
#   mount: kvv2
#   kubernetes:
#     role: compute-provisioner
#     serviceAccount: compute-provisioner
#   vaultConnectionRef: vault-connection
---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultStaticSecret
# metadata:
#   name: vault-static-secret
# spec:
#   vaultAuthRef: vault-auth
#   mount: kvv2
#   type: kv-v2
#   path: deployment
#   refreshAfter: 10s
#   destination:
#     create: true
#     name: vso-handled
