# kubect kubectl ns user-n2232kn234jk34335 && kubectl apply -f vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: user-n2232kn234jk34335
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: deployment
  refreshAfter: 10s
  destination:
    create: true
    name: vso-handled
