# vault kv put kvv2/user-n2232kn234jk34335/deployments/ae72517d-4a1b-463a-ac04-a18daed67a9a REDIS_USERNAME="default" REDIS_PASSWORD="password"
# kubect kubectl ns user-n2232kn234jk34335 && kubectl apply -f k3s/manifests/vault/examples/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: user-n2232kn234jk34335
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: user-n2232kn234jk34335/deployments/ae72517d-4a1b-463a-ac04-a18daed67a9a
  refreshAfter: 10s
  destination:
    create: true
    name: redis-secrets
