# kubectl create ns user-n2232kn234jk34335 && kubectl apply -f k3s/manifests/vault/examples/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: user-n2232kn234jk34335
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: tenant-role
    serviceAccount: default
  vaultConnectionRef: vault-connection
